# Page settings
relativeUrls = true
publishDir = "../"
title = "Seek"
languageCode = "en-us"
theme = "elate"

[params]

  custom_css = ["css/custom1.css", "css/custom2.css"]

  # Meta
  author = ""
  description = ""
  email = ""

  # Google Maps Javascript API Key (if not set will default to not passing a key)
  googleMapsApiKey = ""

  # Navigation
  [params.navigation]
    brand = "<img src='logo.png' alt=logo height='75' width='75'>"
    home = "Home"
    work = "Design Research"
    testimonials = "Interactive Prototype"
    services = "Features"
    about = "Team"

    # You can add custom links before or after the default links
    # Assign a weight to define the order

    # prepended links
    #[[menu.prepend]]
    #  url = "http://gohugo.io"
    #  name = "Hugo"
    #  weight = 10

    # postpended links
    #[[menu.postpend]]
    #  url = "http://gohugo.io"
    #  name = "External link"
    #  weight = 10

  # Hero section
  [params.hero]
    title = "Sexual Education, Empowerment, and Knowledge"
    subtitle = 'Bringing sexual education into the 21st Century.'

  # Intro section
  # Available icons: http://simplelineicons.com/
  [params.intro]

  [[params.intro.item]]
    title = "Sexual Education"
    description = "Only 13 US states currently require that sexual education courses contain scientific and medically accurate information." 
    description2 = "We want to improve the quality of sexual education by enabling access to verifiable information and resources."
    icon = "icon-graduation"
    img = "img_7.jpg"

  [[params.intro.item]]
    title = "Empowerment"
    description = "Sexual education can be sensitive, complex, and difficult to discuss, but it's important for everyone to engage with it." 
    description2 = "We aim to provide students with a comfortable learning environment in which they feel supported and comfortable asking any type of question."
    icon = "icon-energy"
    img = "img_8.jpg"

  [[params.intro.item]]
    title = "Knowledge"
    description = "The breadth and relevance of material covered in generic sex ed classes is often limited." 
    description2 = "We strive to deliver content relevant to the unique identities and interests of students in order to give them knowledge they can actually use in their lives."
    icon = "icon-book-open"
    img = "img_10.jpg"

  [params.intro.video]
    enable = true
    title = "Watch the video"
    icon = "icon-play2"
    url = "youtube.com/v=PrEqrDXWI7Q"


  # Work section
  [params.testimonials]
    enable = true
    title = "Design Research"
    description = 'The first phase of our design process involved creating and refining three different approaches to the problem at hand, ultimately choosing one to pursue. Then, we iterated upon our chosen design and utilized different usability testing methods to solidify each aspect of the application.<br><br> Phase 1 (Getting the Right Design): <a href="firstreport.pdf"> Report </a> and  <a href="pres1.pptx"> Presentation </a><br> Phase 2 (Getting the Design Right): <a href="report.pdf"> Report </a> and <a href="pres2.pptx"> Presentation</a>'
    #footertext = '** Demo images from <a href="http://plmd.me/" target="_blank">plmd.me</a>'

   # Services section
  [params.services]
    enable = true
    title = "Features"
    description = "The SEEK application includes four main features designed to enhance the student experience."

    [[params.services.item]]
      title = "Customizable Agent"
      description = "An agent will lead students through course topics via an interactive video conversation. Students have the ability to customize their agent at any time, changing the agent's appearance or personality to better suit their own preference and comfort level. "
      icon = "icon-user"

    [[params.services.item]]
      title = "Interactive Video Assignments Using AI"
      description = "As students watch each video, they can ask their agent questions to gear the content toward their interests. In turn, the agent will 'learn' more about the student and cater to these preferences, pulling from current sources to keep the conversation engaging."
      icon = "icon-desktop"
      
    [[params.services.item]]
      title = "Anonymous Question Tool"
      description = "Students can ask their teacher a question anonymously via the Anonymous Question tool, free of judgment. Each submitted question becomes a thread in a chat-like window, where students can view responses and submit follow-up questions later on."
      icon = "icon-question"

      [[params.services.item]]
      title = "Resource Center"
      description = "The Resource Center is filled with links to reliable websites. If a student wants to send their teacher a question about something they read online, they can include a link to the website within the Anonymous Question Tool."
      icon = "icon-book-open"

  # Testimonials section
  [params.work]
    enable = true
    title = "Interactive Mockup"
    description = '<iframe style="border: none;" width="800" height="450" src="https://www.figma.com/embed?embed_host=share&url=https%3A%2F%2Fwww.figma.com%2Ffile%2Fg9Zd0ET7d0s0qFwdtUKcErSx%2FSEEK-Digital-Mockup%3Fnode-id%3D1%253A16" allowfullscreen></iframe>'


  # About section
  [params.about]
    enable = true
    title = "Meet the Team"

    [[params.about.item]]
      name = "Haley Ruth"
      position = "Senior Undergraduate<br>Computer Engineering"
      img = "haley.jpg"
      alt = "Person1"
      social = [
        ["icon-facebook", "https://www.facebook.com/haley.ruth.98"],
        ["icon-linkedin", "https://www.linkedin.com/in/haley-ruth/"],
        ["icon-instagram", "https://www.instagram.com/haleymariey/"]
      ]

    [[params.about.item]]
      name = "Laura DeBoldt"
      position = "Junior Undergraduate<br>Computer Science"
      img = "laura.jpg"
      alt = "Person2"
      social = [
        ["icon-facebook", "https://www.facebook.com/laura.deboldt"],
        ["icon-linkedin", "https://www.linkedin.com/in/laura-deboldt/"],
        ["icon-instagram", "https://www.instagram.com/someonelikelaura/"]
      ]

    [[params.about.item]]
      name = "Aishu Murari"
      position = "Junior Undergraduate<br>Computer Science"
      img = "aishu.jpeg"
      alt = "Person4"
      social = [
        ["icon-facebook", "https://www.facebook.com/aishu.murari"],
        ["icon-linkedin", "https://www.linkedin.com/in/aishwarya-murari/"],
        ["icon-instagram", "https://instagram.com/aishu_murari"]
      ]

    [[params.about.item]]
      name = "Max Kern"
      position = "Senior Undergraduate<br>Computer Science"
      img = "max.png"
      alt = "Person5"

      
    [[params.about.item]]
      name = "Jingjing Bu"
      position = "2nd Year Master's<br>Landscape Architecture<br>Urban Planning & Design"
      img = "jingjing.jpg"
      alt = "Person3"
      social = [
        ["icon-facebook", "https://www.facebook.com/cristina.bu.12"],
        ["icon-linkedin", "https://www.linkedin.com/in/jingjingbu206/"],
        ["icon-instagram", "https://www.instagram.com/cloud.bubu/"]
      ]
